export const data=[
    {
    label:"Qesution",
    tag:"TextArea",
    name:"que",
    val:"",
    errormsg:"",
    isShowError:false
    },
    {
        label:"Option1",
        tag:"Input",
        type:"text",
        name:"opt1",
        val:"",
        errormsg:"",
        isShowError:false
        },
    {
        label:"Option2",
        tag:"Input",
        type:"text",
        name:"opt2",
        val:"",
        errormsg:"",
        isShowError:false
            },
    {
        label:"Option3",
        tag:"Input",
        type:"text",
        name:"opt3",
        val:"",
        errormsg:"",
        isShowError:false
                },
    {
        label:"Option4",
        tag:"Input",
        type:"text",
        name:"opt4",
        val:"",
        errormsg:"",
        isShowError:false
                    },
    {
        label:"type",
        options:["Single","Multiple"],
        tag:"Input",
        type:"radio",
        name:"type",
        val:"",
        errormsg:"",
        isShowError:false,
        values:['S','M']
                        },
    {
        label:"Answers",
        tag:"Select",
        answer_options:['A','B','C','D','AB','AC','AD','BC','BD','CD','ABC','ACD','ABD','BCD','ABCD'],
        name:"ans",
        val:"",
        errormsg:"",
        isShowError:false
                            }
                        ]